version: '3.9'


services:
  db:
    image: postgres
    container_name: db_blog
    env_file:
      - .env.dev
    volumes:
      - db_blog_vol:/var/lib/postgresql/data
    ports:
      - 5432:5432

  django:
    container_name: blog
    build: .
    command: sh -c "python manage.py makemigrations --noinput && 
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/Blog
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - .env.dev
    depends_on:
      - db

volumes:
  db_blog_vol: