# Generated by Django 4.2.4 on 2023-08-25 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_blog', '0003_post_post_date_alter_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 25, 22, 30, 3, 82032)),
        ),
    ]
