# Generated by Django 4.2.4 on 2023-08-27 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_blog', '0006_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 27, 13, 29, 22, 909978, tzinfo=datetime.timezone.utc)),
        ),
    ]
