# Generated by Django 4.2.4 on 2023-09-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_blog', '0011_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
